import { useEffect, useMemo, useState } from 'react'
import { addOfficialTaskToStudent, askPrivateQuestion, createRoomPost, loadCommunitySettings, loadRoomRead, markRoomRead, observeAccessibleRooms, observeOfficialTasks, observePrivateQuestions, observeRoomPosts, observeRoomReports, observeUsefulMarks, reportPost, resolveReport, saveCommunitySettings, toggleUsefulMark, updatePostState } from '../services/communityService.js'

function UsefulButton({ classId, roomId, postId, studentId }) {
  const [marks, setMarks] = useState([])
  useEffect(() => observeUsefulMarks({ classId, roomId, postId }, setMarks), [classId, roomId, postId])
  const active = marks.includes(studentId)
  return <button type="button" className="secondary" onClick={() => toggleUsefulMark({ classId, roomId, postId, studentId, active })}>Útil · {marks.length}</button>
}

function RoomBadge({ classId, room, visitedAt, onCount }) {
  useEffect(() => observeRoomPosts({ classId, roomId: room.id }, (posts) => onCount(posts.filter((post) => !visitedAt || (post.createdAt?.toMillis?.() ?? 0) > visitedAt).length), () => {}), [classId, room.id, visitedAt])
  return null
}

export default function CommunitySpace({ classId, role, actorId, actorName, studentId = null }) {
  const [rooms, setRooms] = useState([]); const [roomId, setRoomId] = useState(''); const [posts, setPosts] = useState([])
  const [counts, setCounts] = useState({}); const [visited, setVisited] = useState({}); const [search, setSearch] = useState('')
  const [draft, setDraft] = useState({ type: role === 'tutor' ? 'notice' : 'question', title: '', body: '' }); const [reply, setReply] = useState({})
  const [reports, setReports] = useState([]); const [privateBody, setPrivateBody] = useState(''); const [privateQuestions, setPrivateQuestions] = useState([])
  const [officialTasks, setOfficialTasks] = useState([]); const [settings, setSettings] = useState({ mode: 'daily_summary', quietStart: '21:30', quietEnd: '07:30' })
  const [status, setStatus] = useState({ state: 'idle', message: '' })
  useEffect(() => observeAccessibleRooms({ classId }, (items) => { setRooms(items); setRoomId((current) => current || items[0]?.id || '') }), [classId])
  useEffect(() => { if (!studentId || !rooms.length) return; Promise.all(rooms.map(async (room) => [room.id, await loadRoomRead({ classId, studentId, roomId: room.id })])).then((entries) => setVisited(Object.fromEntries(entries))) }, [classId, studentId, rooms.map((room) => room.id).join('|')])
  useEffect(() => roomId ? observeRoomPosts({ classId, roomId }, setPosts, (error) => setStatus({ state: 'error', message: error.message })) : undefined, [classId, roomId])
  useEffect(() => role === 'tutor' && roomId ? observeRoomReports({ classId, roomId }, setReports, () => {}) : undefined, [classId, roomId, role])
  useEffect(() => observeOfficialTasks({ classId }, setOfficialTasks, () => {}), [classId])
  useEffect(() => studentId ? observePrivateQuestions({ classId, studentId }, setPrivateQuestions, () => {}) : undefined, [classId, studentId])
  useEffect(() => { if (studentId) loadCommunitySettings({ classId, studentId }).then((value) => value && setSettings(value)) }, [classId, studentId])
  const selectRoom = (id) => { setRoomId(id); const now = Date.now(); setVisited({ ...visited, [id]: now }); setCounts({ ...counts, [id]: 0 }); if (studentId) markRoomRead({ classId, studentId, roomId: id }) }
  const parentPosts = useMemo(() => posts.filter((post) => !post.parentPostId && (role === 'tutor' || !post.hidden) && `${post.title} ${post.body}`.toLowerCase().includes(search.toLowerCase())), [posts, role, search])
  const submitPost = async (event) => { event.preventDefault(); try { await createRoomPost({ classId, roomId, author: { role, id: actorId, name: actorName }, input: draft }); setDraft({ ...draft, title: '', body: '' }); setStatus({ state: 'success', message: 'Publicació enviada.' }) } catch (error) { setStatus({ state: 'error', message: error.message }) } }
  const submitReply = async (postId) => { try { await createRoomPost({ classId, roomId, author: { role, id: actorId, name: actorName }, parentPostId: postId, input: { body: reply[postId] } }); setReply({ ...reply, [postId]: '' }) } catch (error) { setStatus({ state: 'error', message: error.message }) } }
  return <section className="community-space">
    <div className="community-heading"><div><p className="eyebrow">Sales per assignatura</p><h2>Comunitat</h2></div><span>Autoria sempre visible</span></div>
    <div className="room-cards">{rooms.map((room) => <button type="button" className={roomId === room.id ? 'room-card active' : 'room-card'} key={room.id} onClick={() => selectRoom(room.id)}>{room.name}{counts[room.id] > 0 && <b>{counts[room.id]}</b>}<RoomBadge classId={classId} room={room} visitedAt={visited[room.id]} onCount={(count) => setCounts((current) => ({ ...current, [room.id]: count }))} /></button>)}</div>
    {roomId && <div className="community-room">
      <div className="community-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cerca a la sala…" /><span>{parentPosts.length} publicacions</span></div>
      <form className="community-post-form" onSubmit={submitPost}><select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value })}>{role === 'student' && <option value="question">Dubte</option>}<option value="resource">Recurs</option>{role === 'tutor' && <option value="notice">Avís</option>}{role === 'tutor' && <option value="question">Pregunta</option>}</select><input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Títol" /><textarea required value={draft.body} onChange={(event) => setDraft({ ...draft, body: event.target.value })} placeholder="Escriu el contingut" /><button>Publica</button></form>
      <div className="community-posts">{parentPosts.map((post) => { const responses = posts.filter((item) => item.parentPostId === post.id && (role === 'tutor' || !item.hidden)); return <article className={`community-post ${post.hidden ? 'hidden' : ''}`} key={post.id}><header><span>{post.type}</span><strong>{post.title}</strong><small>{post.authorName} · {post.authorRole}</small></header><p>{post.body}</p><div className="community-post-actions">{studentId && <UsefulButton classId={classId} roomId={roomId} postId={post.id} studentId={studentId} />}{post.type === 'question' && ((role === 'tutor') || post.authorStudentId === studentId) && <button type="button" className="secondary" onClick={() => updatePostState({ classId, roomId, postId: post.id, changes: { resolved: !post.resolved } })}>{post.resolved ? 'Reobre' : 'Marca resolta'}</button>}{studentId && post.authorStudentId !== studentId && <button type="button" className="secondary" onClick={() => reportPost({ classId, roomId, postId: post.id, studentId, reason: 'Revisió de moderació sol·licitada.' })}>Denuncia</button>}{role === 'tutor' && <button type="button" className="secondary" onClick={() => updatePostState({ classId, roomId, postId: post.id, changes: { hidden: !post.hidden } })}>{post.hidden ? 'Mostra' : 'Oculta'}</button>}</div>{post.resolved && <span className="resolved-badge">Pregunta resolta</span>}<div className="community-replies">{responses.map((item) => <article key={item.id}><p>{item.body}</p><small>{item.authorName}</small>{item.validated && <b>Resposta validada</b>}{role === 'tutor' && <button type="button" onClick={() => updatePostState({ classId, roomId, postId: item.id, changes: { validated: !item.validated } })}>{item.validated ? 'Treu validació' : 'Valida resposta'}</button>}{studentId && <UsefulButton classId={classId} roomId={roomId} postId={item.id} studentId={studentId} />}</article>)}</div><div className="reply-box"><input value={reply[post.id] ?? ''} onChange={(event) => setReply({ ...reply, [post.id]: event.target.value })} placeholder="Respon…" /><button type="button" onClick={() => submitReply(post.id)}>Respon</button></div></article>})}</div>
      {role === 'tutor' && reports.filter((item) => item.status === 'open').map((report) => <div className="moderation-alert" key={report.id}><span>Denúncia pendent sobre una publicació.</span><button type="button" onClick={() => resolveReport({ classId, roomId, reportId: report.id })}>Marca revisada</button></div>)}
    </div>}
    {studentId && <div className="community-side-grid"><form onSubmit={async (event) => { event.preventDefault(); await askPrivateQuestion({ classId, studentId, body: privateBody }); setPrivateBody('') }}><h3>Pregunta privada al tutor</h3><textarea required value={privateBody} onChange={(event) => setPrivateBody(event.target.value)} /><button>Envia en privat</button><small>No és un missatge privat entre alumnes.</small>{privateQuestions.filter((item) => item.response).map((item) => <p key={item.id}><b>Resposta:</b> {item.response}</p>)}</form><form onSubmit={async (event) => { event.preventDefault(); await saveCommunitySettings({ classId, studentId, input: settings }); setStatus({ state: 'success', message: 'Preferències de notificació desades.' }) }}><h3>Notificacions</h3><label>Mode<select value={settings.mode} onChange={(event) => setSettings({ ...settings, mode: event.target.value })}><option value="instant">Avisos dins l’app</option><option value="daily_summary">Resum diari</option><option value="disabled">Desactivades</option></select></label><label>Silenci des de<input type="time" value={settings.quietStart} onChange={(event) => setSettings({ ...settings, quietStart: event.target.value })} /></label><label>Fins a<input type="time" value={settings.quietEnd} onChange={(event) => setSettings({ ...settings, quietEnd: event.target.value })} /></label><button>Desa</button></form></div>}
    {studentId && officialTasks.length > 0 && <section className="official-community-tasks"><h3>Tasques confirmades pel tutor</h3>{officialTasks.map((task) => <article key={task.id}><strong>{task.title}</strong><span>No s’ha afegit automàticament.</span><button type="button" onClick={() => addOfficialTaskToStudent({ classId, studentId, task })}>Afegeix al meu espai</button></article>)}</section>}
    {status.message && <p className={`form-status ${status.state}`}>{status.message}</p>}
  </section>
}
