import { useEffect, useState } from 'react'
import { PROGRESS_STAGES } from '../domain/tutorialAnalytics.js'
import { validateStudySlot } from '../domain/calendarPlanning.js'
import { askPrivateQuestion, observePrivateQuestions } from '../services/communityService.js'
import { markNoticeRead, observeStudentTutorial, respondToSessionSuggestion, submitWeeklyReview } from '../services/tutorialService.js'

const formatDate = (value) => new Intl.DateTimeFormat('ca-AD', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))

export default function StudentTutorialPanel({ session, section = 'messages' }) {
  const [data, setData] = useState({ goal: null, reviews: [], feedback: [], suggestions: [], notices: [], tasks: [] })
  const [review, setReview] = useState({ outcome: 'worked', note: '', helpNeeded: false })
  const [privateBody, setPrivateBody] = useState('')
  const [privateQuestions, setPrivateQuestions] = useState([])
  const [status, setStatus] = useState({ state: 'idle', message: '' })
  useEffect(() => observeStudentTutorial({ classId: session.classId, studentId: session.studentId, includePrivatePlanning: true }, setData, (error) => setStatus({ state: 'error', message: error.message })), [session.classId, session.studentId])
  useEffect(() => observePrivateQuestions({ classId: session.classId, studentId: session.studentId }, setPrivateQuestions, (error) => setStatus({ state: 'error', message: error.message })), [session.classId, session.studentId])
  const submit = async (event) => { event.preventDefault(); setStatus({ state: 'loading', message: 'Desant la revisió…' }); const texts = { worked: ['He identificat què m’ha funcionat.', 'Continuaré amb aquesta estratègia.', 'Mantindré el que funciona.'], difficult: ['He detectat una dificultat.', 'Aquesta setmana hi ha hagut un obstacle.', 'Ho dividiré en un pas més petit.'], adjust: ['He revisat el meu pla.', 'El pla necessita un canvi.', 'Reajustaré temps o prioritat.'] }; try { await submitWeeklyReview({ classId: session.classId, studentId: session.studentId, input: { workedWell: `${texts[review.outcome][0]} ${review.note}`.trim(), wasDifficult: texts[review.outcome][1], nextAdjustment: texts[review.outcome][2], helpNeeded: review.helpNeeded } }); setStatus({ state: 'success', message: 'Revisió setmanal desada.' }) } catch (error) { setStatus({ state: 'error', message: error.message }) } }
  const sendPrivateMessage = async (event) => { event.preventDefault(); if (!privateBody.trim()) return; setStatus({ state: 'loading', message: 'Enviant el missatge…' }); try { await askPrivateQuestion({ classId: session.classId, studentId: session.studentId, body: privateBody }); setPrivateBody(''); setStatus({ state: 'success', message: 'Missatge enviat al tutor.' }) } catch (error) { setStatus({ state: 'error', message: error.message }) } }
  const respond = async (suggestion, accepted) => { const task = data.tasks.find((item) => item.id === suggestion.taskId); if (accepted && !task) return; setStatus({ state: 'loading', message: 'Registrant la teva decisió…' }); try { if (accepted) { const validation = validateStudySlot({ task, scheduledAt: suggestion.scheduledAt, durationMinutes: suggestion.durationMinutes, availability: data.availability, schoolSchedule: session.schoolSchedule, sessions: data.sessions, occupations: data.occupations }); if (!validation.valid) throw new Error(`Aquesta proposta ja no encaixa: ${validation.reason}`) } await respondToSessionSuggestion({ suggestion, task, accepted }); setStatus({ state: 'success', message: accepted ? 'Sessió acceptada i afegida al teu calendari.' : 'Proposta descartada.' }) } catch (error) { setStatus({ state: 'error', message: error.message }) } }
  return (
    <section className="student-tutorial-panel">
      <div className="student-tutorial-heading"><div><p className="eyebrow">{section === 'review' ? 'Una mirada breu' : 'Canal privat'}</p><h2>{section === 'review' ? 'Revisió setmanal' : 'Missatges i seguiment del tutor'}</h2><p>{section === 'review' ? 'Tres opcions ràpides i una nota opcional.' : 'Aquest espai només el podeu veure tu i el teu tutor.'}</p></div></div>
      {section === 'messages' && <><section className="student-private-tutor">
        <div className="private-tutor-intro"><div><span aria-hidden="true">✉</span></div><div><h3>Escriu al tutor</h3><p>Explica-li una preocupació, demana ajuda o comenta-li una situació en privat.</p></div></div>
        <form onSubmit={sendPrivateMessage}><label>Missatge<textarea required maxLength="1000" value={privateBody} onChange={(event) => setPrivateBody(event.target.value)} placeholder="Què vols comentar amb el tutor?" /></label><button>Envia el missatge</button></form>
        {privateQuestions.length > 0 && <div className="private-thread-list"><h3>Converses anteriors</h3>{[...privateQuestions].sort((left, right) => (right.createdAt?.seconds ?? 0) - (left.createdAt?.seconds ?? 0)).map((item) => <article key={item.id}><div><strong>Tu</strong><small>{item.status === 'answered' ? 'Resposta rebuda' : 'Esperant resposta'}</small></div><p>{item.body}</p>{item.response && <blockquote><strong>Tutor</strong><p>{item.response}</p></blockquote>}</article>)}</div>}
      </section>
      {data.notices.filter((item) => !item.readAt).map((notice) => <article className="student-notice" key={notice.id}><strong>{notice.title}</strong><p>{notice.message}</p><button type="button" className="secondary" onClick={() => markNoticeRead({ classId: session.classId, studentId: session.studentId, noticeId: notice.id })}>Marca com a llegit</button></article>)}
      {data.goal && <article className="student-goal"><span>Objectiu tutorial</span><strong>{data.goal.competency}</strong><p>{data.goal.description}</p><small>{PROGRESS_STAGES.find((item) => item.id === data.goal.progressStage)?.label} · no és una nota.</small></article>}
      {data.suggestions.filter((item) => item.status === 'pending').map((item) => <article className="student-suggestion" key={item.id}><strong>El tutor et suggereix una sessió</strong><p>{formatDate(item.scheduledAt)} · {item.durationMinutes} min</p>{item.note && <p>{item.note}</p>}<div className="actions"><button type="button" onClick={() => respond(item, true)}>Accepta i afegeix</button><button type="button" className="secondary" onClick={() => respond(item, false)}>Ara no</button></div><small>El tutor no l’ha afegit al teu calendari: la decisió és teva.</small></article>)}
      <section className="tutor-feedback-list"><h3>Feedback i acords del tutor</h3>{!data.feedback.length && <p>Encara no hi ha feedback.</p>}{data.feedback.map((item) => <article key={item.id}><strong>{item.observation}</strong><p><b>Pregunta:</b> {item.question}</p><p><b>Estratègia:</b> {item.strategy}</p><p><b>Acord:</b> {item.agreement}</p></article>)}</section></>}
      {section === 'review' && <form className="quick-weekly-review" onSubmit={submit}><h3>Quina frase resumeix millor la setmana?</h3><div role="radiogroup" aria-label="Resultat de la setmana">{[['worked', 'M’ha funcionat'], ['difficult', 'M’ha costat'], ['adjust', 'Vull reajustar']].map(([value, label]) => <label className={review.outcome === value ? 'selected' : ''} key={value}><input type="radio" name="review-outcome" value={value} checked={review.outcome === value} onChange={() => setReview({ ...review, outcome: value })} />{label}</label>)}</div><label>Vols afegir algun detall? (opcional)<textarea maxLength="500" value={review.note} onChange={(event) => setReview({ ...review, note: event.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={review.helpNeeded} onChange={(event) => setReview({ ...review, helpNeeded: event.target.checked })} />Vull comentar-ho amb el tutor</label><details><summary>Reflexió més llarga</summary><p>Pots utilitzar el camp opcional per explicar què ha funcionat, què ha costat i què vols reajustar.</p></details><button>Desa la revisió</button></form>}
      {status.message && <p className={`form-status ${status.state}`} role="status">{status.message}</p>}
    </section>
  )
}
