import { useEffect, useMemo, useState } from 'react'
import { buildCommonTaskCorrection, detectCommonTaskContradictions, detectCommonTasks } from '../domain/communityPolicy.js'
import { answerPrivateQuestion, observeCandidateDecisions, observeClassTaskAlerts, observePrivateQuestions, publishContradictionAlert, resolveCommonCandidate, resolveTaskAlert } from '../services/communityService.js'
import { observeTutorClassActivity } from '../services/tutorialService.js'
import CommunitySpace from './CommunitySpace.jsx'

function PrivateQuestionInbox({ classId, students }) {
  const [questions, setQuestions] = useState({}); const [responses, setResponses] = useState({})
  useEffect(() => { const stops = students.map((student) => observePrivateQuestions({ classId, studentId: student.id }, (items) => setQuestions((current) => ({ ...current, [student.id]: items })), () => {})); return () => stops.forEach((stop) => stop()) }, [classId, students.map((item) => item.id).join('|')])
  const open = students.flatMap((student) => (questions[student.id] ?? []).filter((item) => item.status === 'open').map((item) => ({ ...item, studentName: student.displayName })))
  return <section className="private-question-inbox"><h3>Preguntes privades</h3>{!open.length && <p>No hi ha preguntes pendents.</p>}{open.map((item) => <article key={item.id}><strong>{item.studentName}</strong><p>{item.body}</p><textarea value={responses[item.id] ?? ''} onChange={(event) => setResponses({ ...responses, [item.id]: event.target.value })} /><button type="button" onClick={() => answerPrivateQuestion({ classId, studentId: item.ownerStudentId, questionId: item.id, response: responses[item.id] })}>Respon en privat</button></article>)}</section>
}

export default function TutorCommunityPanel({ tutorId, classroom, students }) {
  const [activity, setActivity] = useState({ tasksByStudent: {}, sessionsByStudent: {} }); const [decisions, setDecisions] = useState([]); const [corrections, setCorrections] = useState({}); const [publishedAlerts, setPublishedAlerts] = useState([])
  useEffect(() => observeTutorClassActivity({ classId: classroom.id, students }, setActivity, () => {}), [classroom.id, students.map((item) => item.id).join('|')])
  useEffect(() => observeCandidateDecisions({ classId: classroom.id }, setDecisions), [classroom.id])
  useEffect(() => observeClassTaskAlerts({ classId: classroom.id }, setPublishedAlerts, () => {}), [classroom.id])
  const candidates = useMemo(() => detectCommonTasks({ students, tasksByStudent: activity.tasksByStudent }).filter((candidate) => !decisions.some((decision) => decision.fingerprint === candidate.fingerprint && ['confirmed', 'dismissed'].includes(decision.status))), [students, activity, decisions])
  const contradictions = useMemo(() => detectCommonTaskContradictions({ students, tasksByStudent: activity.tasksByStudent }), [students, activity])
  return <section className="tutor-community-panel"><CommunitySpace classId={classroom.id} role="tutor" actorId={tutorId} actorName="Tutor/a" />
    <section className="common-task-review"><div><p className="eyebrow">Detecció agregada</p><h3>Possibles deures comuns</h3><p>Llindar inicial: tres alumnes. No es mostra cap identitat.</p></div>{students.length < 3 && <p>Calen almenys tres alumnes actius per activar aquesta detecció.</p>}{!candidates.length && students.length >= 3 && <p>No hi ha coincidències pendents de revisió.</p>}{candidates.map((candidate) => { const correction = corrections[candidate.fingerprint] ?? {}; const deadlineValue = correction.deadlineAt ?? (candidate.deadline?.at ? new Date(new Date(candidate.deadline.at).getTime() - new Date(candidate.deadline.at).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''); return <article key={candidate.fingerprint}><span>{candidate.count} coincidències · llindar {candidate.requiredCount}</span><label>Títol<input value={correction.title ?? candidate.title} onChange={(event) => setCorrections((current) => ({ ...current, [candidate.fingerprint]: { ...current[candidate.fingerprint], title: event.target.value } }))} /></label><label>Data corregida<input type="datetime-local" value={deadlineValue} onChange={(event) => setCorrections((current) => ({ ...current, [candidate.fingerprint]: { ...current[candidate.fingerprint], deadlineAt: event.target.value } }))} /></label><div className="actions"><button type="button" onClick={() => resolveCommonCandidate({ tutorId, classId: classroom.id, candidate, action: 'confirmed', correction: buildCommonTaskCorrection({ candidate, title: correction.title, deadlineAt: correction.deadlineAt }) })}>Confirma o corregeix</button><button type="button" className="secondary" onClick={() => resolveCommonCandidate({ tutorId, classId: classroom.id, candidate, action: 'dismissed' })}>Descarta</button></div><small>No s’afegirà a cap alumne automàticament.</small></article> })}</section>
    {contradictions.length > 0 && <section className="common-task-review contradiction-review" aria-labelledby="contradiction-review-title"><div><p className="eyebrow">Alarma per al tutor</p><h3 id="contradiction-review-title">Informació contradictòria</h3><p>Versions agregades d’una possible mateixa tasca. Comprova-les abans de confirmar res.</p></div>{contradictions.map((alarm) => { const published = publishedAlerts.find((item) => item.topicKey === alarm.topicKey && item.status === 'active'); return <article key={alarm.id}><strong>{alarm.title}</strong><span>{alarm.count} alumnes en total · {alarm.variants.length} versions</span><ul>{alarm.variants.map((variant) => <li key={variant.key}><b>{variant.count} coincidències</b> · {variant.key === 'without_date' ? 'sense data' : variant.key}</li>)}</ul><div className="actions">{published ? <button type="button" className="secondary" onClick={() => resolveTaskAlert({ tutorId, classId: classroom.id, alertId: published.id })}>Marca la contradicció com a resolta</button> : <button type="button" onClick={() => publishContradictionAlert({ tutorId, classId: classroom.id, alarm })}>Avisa els alumnes que ho comprovin</button>}</div><small>No es mostra quins alumnes han introduït cada versió.</small></article> })}</section>}
    <PrivateQuestionInbox classId={classroom.id} students={students} />
  </section>
}
